<h1><?php echo $this->translate('Forgot Password'); ?></h1>

<?php
$form = $this->resetPasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('password/request'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">

    	<dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>
