<h1><?php echo $this->translate('Change password'); ?></h1>

<?php
$form = $this->passwordForm;
$form->prepare();
$form->setAttribute('action', $this->url('member/password'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('current')) ?>

        <dt><?php echo $this->formLabel($form->get('current')) ?></dt>
        <dd><?php echo $this->formInput($form->get('current')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('new1')) ?></dt>
        <dd><?php echo $this->formInput($form->get('new1')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('new2')) ?></dt>
        <dd><?php echo $this->formInput($form->get('new2')) ?></dd>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<a href="<?php echo $this->url('member') ?>">[<?php echo $this->translate('Home') ?>]</a> |
<a href="<?php echo $this->url('member/logout'); ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>
